// <auto-generated />
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(clsDbContext))]
    [Migration("20210729125501_v1.1.12")]
    partial class v1112
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.Persona", b =>
                {
                    b.Property<int>("cod_persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Sueldo")
                        .HasColumnType("real");

                    b.Property<int>("cod_sector")
                        .HasColumnType("int");

                    b.Property<int>("cod_zona")
                        .HasColumnType("int");

                    b.Property<string>("fec_nacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_persona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cod_persona");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Backend.Models.Sector", b =>
                {
                    b.Property<int>("cod_sector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("des_sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cod_sector");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("Backend.Models.Zona", b =>
                {
                    b.Property<int>("cod_zona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cod_sector")
                        .HasColumnType("int");

                    b.Property<string>("des_zona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cod_zona");

                    b.ToTable("zonas");
                });
#pragma warning restore 612, 618
        }
    }
}
